import Head from 'next/head'
import { API, Amplify } from 'aws-amplify'
import 'antd/dist/antd.css'
import { listNotes } from '../graphql/queries'
import awsExports from '../aws-exports'
Amplify.configure({ ...awsExports, ssr: true })

export default function Home(props) {
  const { data } = props

  console.log(data)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Try Implement ISR</h1>
      {data.map((v) => (
        <div key={v.id} style={{ marginTop: '10px' }}>
          name = {v.name}
          <br />
          desc = {v.description}
        </div>
      ))}
    </div>
  )
}

export async function getStaticProps() {
  let noteData = await API.graphql({ query: listNotes })
  return {
    props: {
      data: noteData.data.listNotes.items,
    },
  }
}
